apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep
  template:
    metadata:
      labels:
        app: dep
    spec:
      containers:
        - name: todo
          image: myacr.azurecr.io/todo-add-tasks-api
          ports:
            - containerPort: 80


   